---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.5.8
    environment:
      CROSS: "1"
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: install-buildx-support
    image: tonistiigi/binfmt
    privileged: true
    entrypoint:
      - /usr/bin/binfmt
    command:
      - --install
      - all
    when:
      branch:
        - master
      event:
        - tag

  - name: publish-image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      dockerfile: package/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      repo: cnrancher/log-aggregator
      tag: ${DRONE_TAG}
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      refs:
        include:
          - "refs/heads/master"
      event:
        - tag
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
