#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/log-aggregator

if [ "$CROSS" != "" ]; then
    for platform in linux/amd64 linux/arm64
    do
        os="${platform%/*}"
        arch="${platform#*/}"
        mkdir -p "bin/$platform"
        CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o "bin/$platform/log-aggregator"
    done
fi
